dmx:
  port: COM3
center_pan: 181
fixtures:
  bottom: []
  left:
  - adresse: 1
    name: lyre1
    type: LyreSylvain
  other: []
  right:
  - adresse: 12
    name: lyre2
    type: LyreSylvain
  top:
  - adresse: 23
    name: my1
    type: MyLight
window:
  name: Rekordbox
